# Generated by Django 4.0.6 on 2022-08-13 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_group_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(10)], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
