# Generated by Django 4.0.6 on 2022-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_additional_info_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
