# Generated by Django 4.0.6 on 2022-07-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['pk'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
